- _posts/uportal/2016-09-15-myuw-build-now-and-future.md
+ Adds in uportal folder
+ Adds in first uportal post
_Please let me know if there is any additional setup for adding the uportal folder, i couldn't find any_
> Add in post about MyUW Build process

- _posts/uportal/2016-09-15-myuw-build-now-and-future.md
+ add in a return between a paragraph and a bulleted list
+ make subheadings an h2 instead of h1
> Add in proper spacing for ul/li

- _posts/apereo/2016-09-19-newsletter.md
Syndicate [the newsletter](https://groups.google.com/a/apereo.org/d/topic/announcements/y1c-AErU0co/discussion) as a post on apereo.github.io .
An experiment.
> Add lightly edited Sept 15 2016 Apereo newsletter as post.

- _posts/uportal/2016-11-14-web-proxy-overcaching.md
Part of the public disclosure process for WPP-101.
> Add post re Webproxy Portlet overcaching.

- _posts/uportal/2017-01-19-myuw-2016.md
It's that time of year for summarizing and retrospecting.
> Add blog post summarizing MyUW progress in 2016.

- _posts/uportal/2017-01-19-myuw-2016.md
The MyUW 2016 post has been re-posted several places.
Hyperlinks those versions from this version of the post, because [hyperlinks are a good thing](http://aworkinglibrary.com/writing/follow-the-links/).
> Hyperlink the other versions of the myuw2016 post.

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
It'll give us a full 25% more points on our [Community insights](https://github.com/apereo/apereo.github.io/community).
Also, it's just true.
> Note subject to Apereo Welcoming Policy.

- _posts/uportal/2017-06-20-myuw-2016-numbers.md
I think we should recognize our partners
> Add partner teams

- _posts/uportal/2017-06-20-myuw-2016-numbers.md
Minor copy edits.
Add bit about service team.
> Minor edits to myuw-by-the-numbers

- _posts/a11y/2017-08-22-bbd-integrating-a11y-across-lifecycle.md
I had the pleasure of attending the [Better By Design](http://betterbydesignconference.com/) 2017 pre-conference workshop on [integrating accessibility across the design and development lifecycle](http://betterbydesignconference.com/workshops/workshop-accessibility-design-development-life-cycle/). (Presented by [Karl Groves](http://www.karlgroves.com/)). This post captures some points and references I took from the workshop.
> feat(a11y_content): Add post re Better By Design 2017 workshop on a11y

- _posts/uportal/2017-08-30-summer-2017-uportal-roadmap-update.md
> Post summary of uPortal roadmap BOF

- _posts/cas/2018-02-02-OIDC-link-account.md
New article showing some modification we did to CAS
> add new CAS article about <Link OIDC user to existing Database user>

- _posts/uportal/2018-02-20-apache2-chose-uportal.md
Add post partially answering question raised on licensing-discuss@ wrt how existing projects got to the licensing choices they've made.
> feat(uportal): post re how Apache 2 license selected

- _posts/cas/2018-03-30-530rc3-release.md
Document the schema change for MFA trusted devices
> Add release notes about MFA trusted devices

- _posts/apereo/2018-04-20-nominate-to-board.md
Nomination deadline is in 4.5 hours. Maybe there are org reps still looking for names to throw in the hat. Maybe at least putting this out there will start thoughts churning over the next year before the next nomination opportunity.
> add post suggesting nominees for board

- _posts/apereo/2018-04-20-nominate-to-board.md
Fixes for the nomination recommendations post.
> Fix nomination recs post

- about.md
Edit for [brevity](http://thebrieflab.com/brief/).
About page disclaimer:
After:
> Unless otherwise noted, all authors post here wearing their individual Apereo participant [hats](https://www.apache.org/foundation/how-it-works.html#hats). Opinions, statements, and comments expressed via this blog do not necessarily reflect those of the Apereo Foundation.
Before:
> This blog is **BY NO MEANS** an official voice of the Apereo Foundation. All official statements on behalf of the Apereo Foundation are made by the Chair, ED, or other authorized individuals. All opinions, views, notes, anecdotes, stories and comments expressed via this blog solely, purely and exclusively belong to individual authors and do not express or reflect the official policy, position, views or opinions of the Apereo …
> Edit not-official-Apereo disclaimer for brevity.

- _posts/blog/2018-08-24-better-by-design-2018.md
Add a post with notes from Better by Design 2018.
> add Better By Design 2018 post

- _posts/cas/2019-02-18-cas61-saml2-idp-gitlab.md
This describes the process of configuring CAS to authenticate Gitlab via SAML.
> cas saml gitlab post

- _posts/cas/2019-10-25-cas61x-password-management-jdbc.md
Hi Misagh,
Please review and post, if you feel appropriate.
Axel
> Password Management with JDBC

- _posts/cas/2019-11-08-cas61x-jmeter-load-testing.md
> Performance Testing CAS

- _posts/cas/2019-11-27-cas62x-locust-load-testing.md
Article for updated Locust test scripts.
Thanks!
> Load testing with Python Locust

- _posts/cas/2020-02-26-cas-bootiful-client.md
An article on CAS Bootiful Client.  Hope you like!
> CAS Bootiful Client Write-up
